alter table PIZZAS_ORDER_ITEM add constraint FK_PIZZAS_ORDER_ITEM_ON_ORDER foreign key (ORDER_ID) references PIZZAS_ORDER(ID);
alter table PIZZAS_ORDER_ITEM add constraint FK_PIZZAS_ORDER_ITEM_ON_PIZZA foreign key (PIZZA_ID) references PIZZAS_PIZZA(ID);
create index IDX_PIZZAS_ORDER_ITEM_ON_ORDER on PIZZAS_ORDER_ITEM (ORDER_ID);
create index IDX_PIZZAS_ORDER_ITEM_ON_PIZZA on PIZZAS_ORDER_ITEM (PIZZA_ID);
