alter table PIZZAS_INGREDIENT add constraint FK_PIZZAS_INGREDIENT_ON_PIZZA foreign key (PIZZA_ID) references PIZZAS_PIZZA(ID);
alter table PIZZAS_INGREDIENT add constraint FK_PIZZAS_INGREDIENT_ON_TOPPING foreign key (TOPPING_ID) references PIZZAS_TOPPING(ID);
create index IDX_PIZZAS_INGREDIENT_ON_PIZZA on PIZZAS_INGREDIENT (PIZZA_ID);
create index IDX_PIZZAS_INGREDIENT_ON_TOPPING on PIZZAS_INGREDIENT (TOPPING_ID);
